/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ercSol from "./Erc.sol";
export type { ercSol };
export type { StakingContract } from "./StakingContract";
export type { VestingContract } from "./VestingContract";
