/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ercSol from "./Erc.sol";
export { StakingContract__factory } from "./StakingContract__factory";
export { VestingContract__factory } from "./VestingContract__factory";
